const { S3Client, GetObjectCommand, ListObjectsV2Command, DeleteObjectCommand, PutObjectCommand } = require("@aws-sdk/client-s3");
const { getSignedUrl } = require("@aws-sdk/s3-request-presigner");
const { DynamoDBClient, UpdateItemCommand, GetItemCommand } = require("@aws-sdk/client-dynamodb");
const { sendMessage, sendDocument } = require("../utils/whatsapp");
require("dotenv").config();

const s3 = new S3Client({ region: process.env.AWS_REGION || "ap-south-1" });
const dynamo = new DynamoDBClient({ region: process.env.AWS_REGION || "ap-south-1" });

// ─────────────────────────────────────────
// SEND DOCUMENT TO TEACHER
// ─────────────────────────────────────────
async function sendToTeacher(teacherPhone, s3Key, intent, plan) {
  try {
    const downloadUrl = await getSignedUrl(
      s3,
      new GetObjectCommand({
        Bucket: process.env.S3_OUTPUTS_BUCKET || "adira-outputs",
        Key: s3Key
      }),
      { expiresIn: 86400 }
    );

    const filename = `Adira_Class${intent.class}_${intent.subject}_Ch${intent.chapter}_${intent.task.replace(/\s+/g, "")}.pdf`;
    const caption = buildCaption(intent, plan);

    await sendDocument(teacherPhone, downloadUrl, filename, caption);
    console.log(`✅ Document delivered to ${teacherPhone}`);
    return true;

  } catch (error) {
    console.error(`❌ Delivery error:`, error.message);
    await sendMessage(
      teacherPhone,
      `❌ Sorry, there was an issue sending your document.\n\nPlease try your request again.`
    );
    return false;
  }
}

// ─────────────────────────────────────────
// BUILD CAPTION
// ─────────────────────────────────────────
function buildCaption(intent, plan) {
  const emojis = {
    "Lesson Plan": "📝",
    "Worksheet": "📋",
    "Question Paper": "📄"
  };
  const emoji = emojis[intent.task] || "📄";

  return `${emoji} *Your ${intent.task} is Ready!*

📚 *Details:*
- Class: ${intent.class}
- Subject: ${intent.subject}
- Chapter: ${intent.chapter}
${intent.task === "Worksheet" ? `• Questions: ${intent.questionCount}\n` : ""}
✨ _CBSE aligned | NCERT based | Ready to use_

*Need changes?* Just reply:
_"add 5 more questions"_
_"make it harder"_
_"add Hindi translations"_
${plan === "basic" || plan === "pro" ? '\n_"send word file"_ for editable version' : ""}

_Generated by Adira — AI Powered Teacher\'s Assistant_`;
}

// ─────────────────────────────────────────
// SAVE SCHOOL LOGO
// Called when Pro teacher sends logo image
// ─────────────────────────────────────────
async function saveSchoolLogo(teacherPhone, imageData, schoolName, schoolAddress) {
  try {
    // Save logo to S3
    const logoKey = `logos/${teacherPhone}/logo.jpg`;
    await s3.send(new PutObjectCommand({
      Bucket: process.env.S3_OUTPUTS_BUCKET || "adira-outputs",
      Key: logoKey,
      Body: Buffer.from(imageData, "base64"),
      ContentType: "image/jpeg"
    }));

    // Save school details to DynamoDB
    await dynamo.send(new UpdateItemCommand({
      TableName: process.env.DYNAMODB_TABLE || "adira-teachers",
      Key: { phone: { S: teacherPhone } },
      UpdateExpression: "SET schoolName = :name, schoolAddress = :addr, hasLogo = :logo",
      ExpressionAttributeValues: {
        ":name": { S: schoolName || "" },
        ":addr": { S: schoolAddress || "" },
        ":logo": { BOOL: true }
      }
    }));

    await sendMessage(
      teacherPhone,
      `✅ *School Logo Saved!*\n\nYour school logo and name will now appear on all your documents.\n\nWhat would you like to create? 😊`
    );

    console.log(`✅ Logo saved for ${teacherPhone}`);
    return true;

  } catch (error) {
    console.error("❌ Logo save error:", error.message);
    await sendMessage(
      teacherPhone,
      `❌ Sorry, couldn't save your logo. Please try sending it again.`
    );
    return false;
  }
}

// ─────────────────────────────────────────
// GET RECENT DOCUMENTS
// Shows teacher their last 5 documents
// ─────────────────────────────────────────
async function getRecentDocuments(teacherPhone) {
  try {
    const result = await s3.send(new ListObjectsV2Command({
      Bucket: process.env.S3_OUTPUTS_BUCKET || "adira-outputs",
      Prefix: `outputs/${teacherPhone}/`,
      MaxKeys: 5
    }));

    if (!result.Contents || result.Contents.length === 0) {
      return [];
    }

    const sorted = result.Contents.sort(
      (a, b) => b.LastModified - a.LastModified
    );

    const documents = await Promise.all(
      sorted.map(async (file) => {
        const url = await getSignedUrl(
          s3,
          new GetObjectCommand({
            Bucket: process.env.S3_OUTPUTS_BUCKET || "adira-outputs",
            Key: file.Key
          }),
          { expiresIn: 3600 }
        );
        return {
          filename: file.Key.split("/").pop(),
          url: url,
          date: file.LastModified
        };
      })
    );

    return documents;

  } catch (error) {
    console.error("❌ Get recent docs error:", error.message);
    return [];
  }
}

// ─────────────────────────────────────────
// SEND RENEWAL REMINDER
// Called 3 days before plan expiry
// ─────────────────────────────────────────
async function sendRenewalReminder(teacherPhone, plan, expiryDate) {
  const expiryStr = new Date(expiryDate).toLocaleDateString("en-IN", {
    day: "numeric", month: "long", year: "numeric"
  });

  const secrets = require("../utils/secrets");
  const s = await secrets.getSecrets();
  const link = plan === "basic"
    ? (s.RAZORPAY_BASIC_LINK || process.env.RAZORPAY_BASIC_LINK)
    : (s.RAZORPAY_PRO_LINK || process.env.RAZORPAY_PRO_LINK);

  const price = plan === "basic" ? "199" : "399";

  await sendMessage(
    teacherPhone,
    `⏰ *Plan Expiring Soon!*

Your *${plan.charAt(0).toUpperCase() + plan.slice(1)} Plan* expires on *${expiryStr}*.

Renew now to avoid interruption:
💳 Pay ₹${price}: ${link}

Your plan will auto-renew after payment ✅`
  );

  console.log(`✅ Renewal reminder sent to ${teacherPhone}`);
}

// ─────────────────────────────────────────
// CLEANUP OLD FILES
// Run weekly via CloudWatch Events
// Deletes PDFs older than 7 days
// ─────────────────────────────────────────
async function cleanupOldFiles() {
  try {
    const sevenDaysAgo = new Date();
    sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

    const listResult = await s3.send(new ListObjectsV2Command({
      Bucket: process.env.S3_OUTPUTS_BUCKET || "adira-outputs",
      Prefix: "outputs/"
    }));

    if (!listResult.Contents) return;

    const oldFiles = listResult.Contents.filter(
      file => file.LastModified < sevenDaysAgo
    );

    for (const file of oldFiles) {
      await s3.send(new DeleteObjectCommand({
        Bucket: process.env.S3_OUTPUTS_BUCKET || "adira-outputs",
        Key: file.Key
      }));
      console.log(`🗑️ Deleted: ${file.Key}`);
    }

    console.log(`✅ Cleanup done. Deleted ${oldFiles.length} files.`);

  } catch (error) {
    console.error("❌ Cleanup error:", error.message);
  }
}

module.exports = {
  sendToTeacher,
  saveSchoolLogo,
  getRecentDocuments,
  sendRenewalReminder,
  cleanupOldFiles
};