const { S3Client, GetObjectCommand, ListObjectsV2Command, DeleteObjectCommand } = require("@aws-sdk/client-s3");
const { getSignedUrl } = require("@aws-sdk/s3-request-presigner");
const { sendMessage, sendDocument } = require("../utils/whatsapp");
require("dotenv").config();

const s3 = new S3Client({ region: process.env.AWS_REGION || "ap-south-1" });

// ─────────────────────────────────────────
// SEND DOCUMENT TO TEACHER
// Called after PDF is created and uploaded
// ─────────────────────────────────────────
async function sendToTeacher(teacherPhone, s3Key, intent) {
  try {
    // Generate a secure download link
    // Valid for 24 hours — enough time for teacher to download
    const downloadUrl = await getSignedUrl(
      s3,
      new GetObjectCommand({
        Bucket: process.env.S3_OUTPUTS_BUCKET || "adira-outputs",
        Key: s3Key
      }),
      { expiresIn: 86400 } // 24 hours
    );

    // Create a clean filename for the teacher
    const filename = `Adira_Class${intent.class}_${intent.subject}_Ch${intent.chapter}_${intent.task.replace(/\s+/g, "")}.pdf`;

    // Create a friendly caption message
    const caption = buildCaption(intent);

    // Send the document via WhatsApp
    await sendDocument(teacherPhone, downloadUrl, filename, caption);

    console.log(`✅ Document delivered to ${teacherPhone}`);
    return true;

  } catch (error) {
    console.error(`❌ Delivery error for ${teacherPhone}:`, error.message);

    // If delivery fails — send a text message instead
    await sendMessage(
      teacherPhone,
      `❌ Sorry, there was an issue sending your document.\n\nPlease try your request again and I'll create a fresh copy for you.`
    );
    return false;
  }
}

// ─────────────────────────────────────────
// BUILD CAPTION MESSAGE
// The text shown with the PDF on WhatsApp
// ─────────────────────────────────────────
function buildCaption(intent) {
  const taskEmojis = {
    "Lesson Plan": "📝",
    "Worksheet": "📋",
    "Question Paper": "📄"
  };

  const emoji = taskEmojis[intent.task] || "📄";

  return `${emoji} *Your ${intent.task} is Ready!*

📚 *Details:*
- Class: ${intent.class}
- Subject: ${intent.subject}  
- Chapter: ${intent.chapter}
${intent.task === "Worksheet" ? `• Questions: ${intent.questionCount}` : ""}

✨ _CBSE aligned | NCERT based | Ready to use_

_Generated by Adira — AI Powered Teacher's Assistant_`;
}

// ─────────────────────────────────────────
// CLEANUP OLD FILES
// Deletes PDFs older than 7 days from S3
// Keeps storage costs minimal
// Run this once a week via CloudWatch Events
// ─────────────────────────────────────────
async function cleanupOldFiles() {
  try {
    const sevenDaysAgo = new Date();
    sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

    // List all files in outputs bucket
    const listResult = await s3.send(new ListObjectsV2Command({
      Bucket: process.env.S3_OUTPUTS_BUCKET || "adira-outputs",
      Prefix: "outputs/"
    }));

    if (!listResult.Contents) return;

    // Find files older than 7 days
    const oldFiles = listResult.Contents.filter(
      file => file.LastModified < sevenDaysAgo
    );

    // Delete old files
    for (const file of oldFiles) {
      await s3.send(new DeleteObjectCommand({
        Bucket: process.env.S3_OUTPUTS_BUCKET || "adira-outputs",
        Key: file.Key
      }));
      console.log(`🗑️ Deleted old file: ${file.Key}`);
    }

    console.log(`✅ Cleanup complete. Deleted ${oldFiles.length} old files.`);

  } catch (error) {
    console.error("❌ Cleanup error:", error.message);
  }
}

// ─────────────────────────────────────────
// GET TEACHER'S RECENT DOCUMENTS
// Shows teacher their last 5 generated docs
// ─────────────────────────────────────────
async function getRecentDocuments(teacherPhone) {
  try {
    const result = await s3.send(new ListObjectsV2Command({
      Bucket: process.env.S3_OUTPUTS_BUCKET || "adira-outputs",
      Prefix: `outputs/${teacherPhone}/`,
      MaxKeys: 5
    }));

    if (!result.Contents || result.Contents.length === 0) {
      return [];
    }

    // Sort by date — newest first
    const sorted = result.Contents.sort(
      (a, b) => b.LastModified - a.LastModified
    );

    // Generate fresh download links for each
    const documents = await Promise.all(
      sorted.map(async (file) => {
        const url = await getSignedUrl(
          s3,
          new GetObjectCommand({
            Bucket: process.env.S3_OUTPUTS_BUCKET || "adira-outputs",
            Key: file.Key
          }),
          { expiresIn: 3600 } // 1 hour
        );
        return {
          filename: file.Key.split("/").pop(),
          url: url,
          date: file.LastModified
        };
      })
    );

    return documents;

  } catch (error) {
    console.error("❌ Get recent docs error:", error.message);
    return [];
  }
}

module.exports = { sendToTeacher, cleanupOldFiles, getRecentDocuments };