const { SQSClient } = require("@aws-sdk/client-sqs");
const { DynamoDBClient, UpdateItemCommand, GetItemCommand } = require("@aws-sdk/client-dynamodb");
const { S3Client, PutObjectCommand, GetObjectCommand } = require("@aws-sdk/client-s3");
const { getSignedUrl } = require("@aws-sdk/s3-request-presigner");
const { sendMessage, sendDocument } = require("../utils/whatsapp");
const { generateLessonPlan } = require("../prompts/lessonPlan");
const { generateWorksheet } = require("../prompts/worksheet");
const { generateQuestionPaper } = require("../prompts/questionPaper");
const { checkSubscription, getBlockMessage, PLANS } = require("../utils/payments");
const { PDFDocument, StandardFonts, rgb } = require("pdf-lib");
require("dotenv").config();

const dynamo = new DynamoDBClient({ region: process.env.AWS_REGION || "ap-south-1" });
const s3 = new S3Client({ region: process.env.AWS_REGION || "ap-south-1" });

// ─────────────────────────────────────────
// MAIN HANDLER
// Triggered by SQS
// ─────────────────────────────────────────
async function handler(event) {
  for (const record of event.Records) {
    try {
      const job = JSON.parse(record.body);
      console.log(`⚙️ Processing job for ${job.teacherPhone}`);
      await processJob(job);
    } catch (error) {
      console.error("❌ Job error:", error.message);
      try {
        const job = JSON.parse(record.body);
        await sendMessage(
          job.teacherPhone,
          `❌ Sorry, something went wrong while creating your document.\n\nPlease try again:\n_"lesson plan class 7 science chapter 3"_`
        );
      } catch(e) {
        console.error("❌ Could not send error message:", e.message);
      }
    }
  }
}

// ─────────────────────────────────────────
// PROCESS A SINGLE JOB
// ─────────────────────────────────────────
async function processJob(job) {
  const { teacherPhone, intent } = job;

  // ── Step 1: Get teacher & check subscription ──
  const teacher = await getTeacher(teacherPhone);
  const subCheck = await checkSubscription(teacher);

  if (!subCheck.allowed) {
    await sendMessage(teacherPhone, getBlockMessage(subCheck.reason, subCheck.plan));
    return;
  }

  // ── Step 2: Generate content ──
  console.log(`🤖 Generating ${intent.task} — Class ${intent.class} ${intent.subject} Ch${intent.chapter}`);
  let generatedContent = "";

  if (intent.task === "Lesson Plan") {
    generatedContent = await generateLessonPlan(intent);
  } else if (intent.task === "Worksheet") {
    generatedContent = await generateWorksheet(intent);
  } else if (intent.task === "Question Paper") {
    generatedContent = await generateQuestionPaper(intent);
  }

  // ── Step 3: Create PDF ──
  console.log("📄 Creating PDF...");
  const pdfBytes = await createPDF(generatedContent, intent);

  // ── Step 4: Upload PDF to S3 ──
  const filename = `Class${intent.class}_${intent.subject}_Ch${intent.chapter}_${intent.task.replace(/\s+/g, "")}_${Date.now()}.pdf`;
  const s3Key = `outputs/${teacherPhone}/${filename}`;

  await s3.send(new PutObjectCommand({
    Bucket: process.env.S3_OUTPUTS_BUCKET || "adira-outputs",
    Key: s3Key,
    Body: pdfBytes,
    ContentType: "application/pdf"
  }));

  // ── Step 5: Generate download URL ──
  const downloadUrl = await getSignedUrl(
    s3,
    new GetObjectCommand({
      Bucket: process.env.S3_OUTPUTS_BUCKET || "adira-outputs",
      Key: s3Key
    }),
    { expiresIn: 86400 }
  );

  // ── Step 6: Send PDF to teacher ──
  const plan = teacher?.plan?.S || "trial";
  const caption = buildCaption(intent, plan, subCheck.remaining);

  await sendDocument(teacherPhone, downloadUrl, filename, caption);

  // ── Step 7: Update usage ──
  const currentUsage = parseInt(teacher?.generationsThisMonth?.N || "0");
  await updateUsage(teacherPhone, currentUsage + 1);

  console.log(`✅ Job complete for ${teacherPhone}`);
}

// ─────────────────────────────────────────
// BUILD CAPTION
// Message shown with PDF on WhatsApp
// ─────────────────────────────────────────
function buildCaption(intent, plan, remaining) {
  const taskEmojis = {
    "Lesson Plan": "📝",
    "Worksheet": "📋",
    "Question Paper": "📄"
  };
  const emoji = taskEmojis[intent.task] || "📄";
  const remainingText = plan === "pro"
    ? "Unlimited"
    : `${remaining} remaining this month`;

  return `${emoji} *Your ${intent.task} is Ready!*

📚 Class ${intent.class} | ${intent.subject} | Chapter ${intent.chapter}
✨ CBSE aligned | NCERT based

📊 Generations: ${remainingText}

*Need changes?*
Reply with what to change:
_"add 5 more questions on photosynthesis"_
_"make it bilingual Hindi+English"_
${plan !== "free" ? '_"send word file"_ for editable version' : ""}

_Generated by Adira — AI Powered Teacher's Assistant_`;
}

// ─────────────────────────────────────────
// CREATE PDF
// ─────────────────────────────────────────
async function createPDF(content, intent) {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const pageWidth = 595;
  const pageHeight = 842;
  const margin = 50;
  const lineHeight = 16;
  const fontSize = 10;

  let page = pdfDoc.addPage([pageWidth, pageHeight]);
  let y = pageHeight - margin;

  // Header
  page.drawText("ADIRA — AI Powered Teacher's Assistant", {
    x: margin, y: y, size: 12,
    font: boldFont, color: rgb(0.15, 0.39, 0.92)
  });
  y -= 20;

  page.drawText(
    `Class ${intent.class} | ${intent.subject} | Chapter ${intent.chapter} | ${intent.task}`,
    { x: margin, y: y, size: 10, font: font, color: rgb(0.4, 0.4, 0.4) }
  );
  y -= 10;

  page.drawLine({
    start: { x: margin, y: y },
    end: { x: pageWidth - margin, y: y },
    thickness: 1, color: rgb(0.15, 0.39, 0.92)
  });
  y -= 20;

  // Content
  const lines = content.split("\n");
  for (const line of lines) {
    if (y < margin + 40) {
      page = pdfDoc.addPage([pageWidth, pageHeight]);
      y = pageHeight - margin;
    }

    const isDivider = line.includes("━━━");
    if (isDivider) {
      page.drawLine({
        start: { x: margin, y: y },
        end: { x: pageWidth - margin, y: y },
        thickness: 0.5, color: rgb(0.8, 0.8, 0.8)
      });
      y -= lineHeight;
      continue;
    }

    const cleanLine = line.replace(/\*/g, "").replace(/━/g, "").trim();
    if (!cleanLine) { y -= lineHeight / 2; continue; }

    const isHeading = line.trim().startsWith("**") || 
                      line.toUpperCase() === line && line.length > 3;

    const words = cleanLine.split(" ");
    let currentLine = "";
    const maxWidth = pageWidth - margin * 2;

    for (const word of words) {
      const testLine = currentLine + (currentLine ? " " : "") + word;
      const testWidth = (isHeading ? boldFont : font)
        .widthOfTextAtSize(testLine, fontSize);

      if (testWidth > maxWidth && currentLine) {
        if (y < margin + 40) {
          page = pdfDoc.addPage([pageWidth, pageHeight]);
          y = pageHeight - margin;
        }
        page.drawText(currentLine, {
          x: margin, y: y, size: fontSize,
          font: isHeading ? boldFont : font,
          color: isHeading ? rgb(0.15, 0.39, 0.92) : rgb(0, 0, 0)
        });
        y -= lineHeight;
        currentLine = word;
      } else {
        currentLine = testLine;
      }
    }

    if (currentLine) {
      if (y < margin + 40) {
        page = pdfDoc.addPage([pageWidth, pageHeight]);
        y = pageHeight - margin;
      }
      page.drawText(currentLine, {
        x: margin, y: y, size: fontSize,
        font: isHeading ? boldFont : font,
        color: isHeading ? rgb(0.15, 0.39, 0.92) : rgb(0, 0, 0)
      });
      y -= lineHeight;
    }
  }

  // Footer on every page
  const pages = pdfDoc.getPages();
  pages.forEach((p, i) => {
    p.drawText(
      `Generated by Adira | Page ${i + 1} of ${pages.length} | ${new Date().toLocaleDateString("en-IN")}`,
      { x: margin, y: 30, size: 8, font: font, color: rgb(0.6, 0.6, 0.6) }
    );
  });

  return await pdfDoc.save();
}

// ─────────────────────────────────────────
// GET TEACHER
// ─────────────────────────────────────────
async function getTeacher(phone) {
  try {
    const result = await dynamo.send(new GetItemCommand({
      TableName: process.env.DYNAMODB_TABLE || "adira-teachers",
      Key: { phone: { S: phone } }
    }));
    return result.Item || null;
  } catch (error) {
    console.error("❌ Get teacher error:", error.message);
    return null;
  }
}

// ─────────────────────────────────────────
// UPDATE USAGE COUNT
// ─────────────────────────────────────────
async function updateUsage(phone, newCount) {
  try {
    await dynamo.send(new UpdateItemCommand({
      TableName: process.env.DYNAMODB_TABLE || "adira-teachers",
      Key: { phone: { S: phone } },
      UpdateExpression: "SET generationsThisMonth = :count, lastActive = :date",
      ExpressionAttributeValues: {
        ":count": { N: newCount.toString() },
        ":date":  { S: new Date().toISOString() }
      }
    }));
  } catch (error) {
    console.error("❌ Update usage error:", error.message);
  }
}

module.exports = { handler };